### ISSUE TITLE
[BE] Upgrade the project to Laravel 11

### ISSUE THREAD

**Issue by davorminchorov** [learnhubmkd/api#10]
### Task Requirements
We can upgrade the API to Laravel 11 when it comes out on March 12 2024.

[Follow the upgrade guide](https://laravel.com/docs/11.x/upgrade) to do the upgrade.

**Comment by jovangjokovski** [comment]
Merge conflicts:

-   required package mockery 2.1.0 but unstable version
-   app/admin conflict

On hold until further notice.

**Comment by davorminchorov** [comment]
@jovangjokovski Mockery 1.6.9 should have support for Laravel 11 since it's a default dependency.

The version 2.1.0 was specifically for internachi/laravel-modular which adds support for Laravel 11.

**Comment by jovangjokovski** [comment]
It was Mockery 1.6.9 . I have redacted my [comment](https://github.com/learnhubmkd/api/issues/10#issuecomment-2009034310). Will revisit this when they resolve the issue. 
![mockery](https://github.com/learnhubmkd/api/assets/161839742/23b13dfc-9d48-4155-9101-bfd5123823ce)
