### ISSUE TITLE
[BE] Set up PHP CS Fixer

### ISSUE THREAD

**Issue by davorminchorov** [learnhubmkd/api#12]
### Task Requirement

We need a consistent code style so we need to install PHP CS Fixer to the project which will automatically fix style issues.

We also need to implement a custom GitHub Action which will trigger the checks on the pull request and check for style issues.

We will follow the PSR-12 coding standard, until PHP CS Fixer gets support for PER 2.0

**Comment by bzrncev** [comment]
Maybe we can install Laravel Pint - https://laravel.com/docs/10.x/pint which is build on top of CS fixer

**Comment by davorminchorov** [comment]
Yeah, Laravel Pint works as well, we can use it.

**Comment by davorminchorov** [comment]
@Kika86 we will also need a GitHub Action setup to run the style checks and find any issues which will force people to fix their styles before committing the code.

Also, please configure it so that it uses PSR-12 as a style guide instead of the Laravel one.
