### ISSUE TITLE
[BE] Improve the email address validation for contact and newsletter subscription API endpoints

### ISSUE THREAD

**Issue by davorminchorov** [learnhubmkd/api#126]
### Task Requirements

Currently, we are validating the email addresses for both contact and newsletter subscription API endpoints but that's not enough.

People can still send fake email addresses and it will cause the emails to bounce. 

We need to verify that the email address that is being used in the form is valid by adding additional validation rules:
```
'email' => 'email:rfc,dns'
```

Additionally, we can integrate something like Mailbox Layer to actually verify the email addresses and reduce the potential spam by bots or malicious actors.

You can find details on how to integrate it by [checking out this tutorial](https://ashallendesign.co.uk/blog/how-to-validate-email-addresses-using-laravel-mailbox-layer)

I'll provide you with the API keys.

**Comment by KalimeroMK** [comment]
@davorminchorov paketot so si go preporacal e staj go frknav i abedjtutvav da raboti na laravel11 da cekam sopstvenikot da go abdejtuva ili da ja koristaj mojata verzija

**Comment by davorminchorov** [comment]
I didn’t notice that the package was old, I’ll look for an alternative package or if the API still works, you can probably integrate it manually based on the package that I linked.

**Comment by KalimeroMK** [comment]
@davorminchorov I will do the integration without  package no need :)
