### ISSUE TITLE
[BE] Implement the blog posts API endpoint

### ISSUE THREAD

**Issue by davorminchorov** [learnhubmkd/api#35]
## Business Requirements

As a visitor, I want to be able to read blog posts on the website so that I can learn more about the initiative.

## Acceptance Criteria
1. There should be an API endpoint which will retrieve all published blog posts, paginated, 15 items per page, ordered by the publish date.
2. There should be an ability to search the blog posts by title
3. The blog posts endpoint should retrieve the following details for each blog post: 
- Title
- Slug
- Excerpt
- Author name
- Author profile image
- Publish Date
- Tags
4. An API documentation should b e implemented with Scribe for the endpoint so that it will be easier for the frontend team to integrate it.

**Comment by davorminchorov** [comment]
@nikoladomazetovikj I looked at your PR, and it reminded me about a few things that I initially missed in this ticket.

The blog will be for people with LearnHub Marketing role access (at the start, we may expand this as a blogging platform for each member of the platform later on) which means we want to split it from the actual user object. 

It should have a separate author profile table which will be related to the blog posts table so that we don't mix the same profile from the platform with the author profile.

The author profile should have:
- First Name
- Last Name
- Profile Picture
- Bio
- Website URL
- LinkedIn Profile URL

Also, tags should be a separate table on its own which would require a many to many relationship with the blog posts. 

The same goes for #36 

The API should follow the REST principles.

**Comment by nikoladomazetovikj** [comment]
@davorminchorov this is the ER diagram of current database design 
![image](https://github.com/learnhubmkd/api/assets/58082595/310c081a-65a5-4575-9596-ac6ad07403ef)

We can also add `status` in the `blogs` table, for e.g.:

- `draft` - author still editing the post 
- `published` - ready to display in the blog list
- `review` - in case we want to check blogs before publishing 

Additionally should we use `soft deletes` ?

**Comment by davorminchorov** [comment]
The ER Diagram looks good, you can move the name from the users table to first_name and last_name in the authors table.

Also, rename blogs to blog_posts for the table and every other reference in the code.

The statuses look good, maybe change review to in_review and add archived.

Use enums for the statuses.

I know that having soft deletes is a popular thing but we wouldn't need soft deletes for this project. They are very complex to manage for no real benefit.

Having an audit table for each action could help to track the changes for every action in the system.
