### ISSUE TITLE
[BE] Implement Member Sign Up API

### ISSUE THREAD

**Issue by davorminchorov** [learnhubmkd/api#45]
## Business Requirements
As a visitor, I want to be able to sign up with email address and password to the platform so that I can use the platform

## Acceptance criteria
- [x] There should be an endpoint to allow for members to sign up
- [x] The member details should contain the following fields: 
- Authentication details (email address, password)
- Profile details (first name, last name, image)
- [x] The role should be set to `Member` by default
- [x] There should be request validation.
- [x] An activation email should be sent when the member signs up
- [x] A welcome email should be sent when the member verifies their email address.
- [x] There should be a API rate limiting of 5 requests per minute.
- [x] There should be API documentation generated by Scribe so that the frontend team can easily integrate it.

**Comment by nikoladomazetovikj** [comment]
@davorminchorov for the image, should we accept URL from some external source or we need to store in locally on the server?

**Comment by davorminchorov** [comment]
@nikoladomazetovikj you can store the files locally for now, but we can move the files to S3 later on.

**Comment by nikoladomazetovikj** [comment]
@davorminchorov FYI this ticket will be done by the EOW. Sorry for the delay
