### ISSUE TITLE
[BE] Split the installation instructions in the readme based on operating system

### ISSUE THREAD

**Issue by davorminchorov** [learnhubmkd/api#55]
### Task Requirements

We need to split the installation instructions in the readme based on operating system for the API repository so that it is easier for new people to set up the project.

**Comment by RevanchistX** [comment]
@davorminchorov I don't know which commands work on the other systems.

**Comment by davorminchorov** [comment]
@RevanchistX Split them for Linux / Mac and Windows or the current ones into separate sections.

**Comment by RevanchistX** [comment]
@stoimenov95 you were the one who noticed the inconsistency. Can you provide more info as what you'd like to be included in the readme? I am kinda lost to which parts are malfunctioning for you.

**Comment by stoimenov95** [comment]
hey @RevanchistX, as Davor mentioned above, it would be great if you could separate the sections (OS-based). I had some trouble specifically with the WSL commands because they were included in the steps, but they are needed only for Windows.
